/**
 * Каждый герой открывает свою башню (поле tower).
 * Бонусы суммируются по всем открытым героям.
 */
var HEROES = [
  {
    id: "ember",
    name: "Эмбер",
    role: "Урон башен +4%",
    rarity: "common",
    gradient: "linear-gradient(145deg, #f97316, #7c2d12)",
    bonus: { damageMul: 1.04 },
    tower: {
      name: "Жар-луч",
      mechanic: "burn",
      mechanicDesc: "Поджог: периодический урон",
      cost: 82,
      range: 116,
      damage: 15,
      cooldown: 40,
      color: "#fb923c",
      splash: 0,
      slow: 0,
    },
  },
  {
    id: "frost",
    name: "Люмис",
    role: "Замедление эффектов +5%",
    rarity: "common",
    gradient: "linear-gradient(145deg, #38bdf8, #1e3a5f)",
    bonus: { slowMul: 1.05 },
    tower: {
      name: "Ледяной шип",
      mechanic: "deep_chill",
      mechanicDesc: "Мороз: сильное замедление",
      cost: 95,
      range: 104,
      damage: 9,
      cooldown: 44,
      color: "#38bdf8",
      splash: 0,
      slow: 0.34,
    },
  },
  {
    id: "mira",
    name: "Мира",
    role: "Дальность +2%",
    rarity: "common",
    gradient: "linear-gradient(145deg, #4ade80, #14532d)",
    bonus: { rangeMul: 1.02 },
    tower: {
      name: "Терновый выстрел",
      mechanic: "pierce",
      mechanicDesc: "Пробивает до 2 целей подряд",
      cost: 78,
      range: 120,
      damage: 13,
      cooldown: 42,
      color: "#4ade80",
      splash: 0,
      slow: 0,
    },
  },
  {
    id: "spark",
    name: "Спарк",
    role: "Скорострельность +3%",
    rarity: "common",
    gradient: "linear-gradient(145deg, #fde047, #854d0e)",
    bonus: { rateMul: 1.03 },
    tower: {
      name: "Искровой залп",
      mechanic: "double_tap",
      mechanicDesc: "Два быстрых выстрела подряд",
      cost: 88,
      range: 108,
      damage: 11,
      cooldown: 28,
      color: "#facc15",
      splash: 0,
      slow: 0,
    },
  },
  {
    id: "drake",
    name: "Дрейк",
    role: "Урон +3%",
    rarity: "common",
    gradient: "linear-gradient(145deg, #ef4444, #7f1d1d)",
    bonus: { damageMul: 1.03 },
    tower: {
      name: "Драконий град",
      mechanic: "fireball",
      mechanicDesc: "Взрыв по области",
      cost: 105,
      range: 100,
      damage: 18,
      cooldown: 72,
      color: "#f87171",
      splash: 38,
      slow: 0,
    },
  },
  {
    id: "vera",
    name: "Вера",
    role: "Дальность башен +3%",
    rarity: "rare",
    gradient: "linear-gradient(145deg, #34d399, #065f46)",
    bonus: { rangeMul: 1.03 },
    tower: {
      name: "Снайпер",
      mechanic: "longshot",
      mechanicDesc: "Бонус урона на дальней дистанции",
      cost: 125,
      range: 148,
      damage: 22,
      cooldown: 62,
      color: "#34d399",
      splash: 0,
      slow: 0,
    },
  },
  {
    id: "orin",
    name: "Орин",
    role: "Золото за убийство +6%",
    rarity: "rare",
    gradient: "linear-gradient(145deg, #fbbf24, #92400e)",
    bonus: { goldMul: 1.06 },
    tower: {
      name: "Золотая батарея",
      mechanic: "midas",
      mechanicDesc: "Доп. золото за убийство этой башней",
      cost: 138,
      range: 102,
      damage: 26,
      cooldown: 88,
      color: "#fbbf24",
      splash: 44,
      slow: 0,
    },
  },
  {
    id: "dune",
    name: "Дюна",
    role: "Бронебойный урон +5%",
    rarity: "rare",
    gradient: "linear-gradient(145deg, #d6d3d1, #57534e)",
    bonus: { damageMul: 1.05 },
    tower: {
      name: "Песчаный снаряд",
      mechanic: "armor_pierce",
      mechanicDesc: "Игнорирует часть брони",
      cost: 132,
      range: 110,
      damage: 30,
      cooldown: 90,
      color: "#a8a29e",
      splash: 0,
      slow: 0,
    },
  },
  {
    id: "riven",
    name: "Ривен",
    role: "Урон +4%",
    rarity: "rare",
    gradient: "linear-gradient(145deg, #c084fc, #581c87)",
    bonus: { damageMul: 1.04 },
    tower: {
      name: "Клинки тени",
      mechanic: "shrapnel",
      mechanicDesc: "Осколок бьёт вторую цель рядом",
      cost: 128,
      range: 98,
      damage: 16,
      cooldown: 36,
      color: "#c084fc",
      splash: 32,
      slow: 0,
    },
  },
  {
    id: "thorne",
    name: "Торн",
    role: "Замедление +3%",
    rarity: "rare",
    gradient: "linear-gradient(145deg, #65a30d, #365314)",
    bonus: { slowMul: 1.03 },
    tower: {
      name: "Ядовитый шип",
      mechanic: "poison",
      mechanicDesc: "Яд: урон со временем",
      cost: 118,
      range: 106,
      damage: 10,
      cooldown: 46,
      color: "#84cc16",
      splash: 0,
      slow: 0.4,
    },
  },
  {
    id: "kael",
    name: "Каэль",
    role: "Скорострельность +4%",
    rarity: "rare",
    gradient: "linear-gradient(145deg, #7dd3fc, #0369a1)",
    bonus: { rateMul: 1.04 },
    tower: {
      name: "Рунический луч",
      mechanic: "chain",
      mechanicDesc: "Цепная молния ко второй цели",
      cost: 122,
      range: 114,
      damage: 17,
      cooldown: 34,
      color: "#7dd3fc",
      splash: 0,
      slow: 0,
    },
  },
  {
    id: "elara",
    name: "Элара",
    role: "Дальность +4%",
    rarity: "rare",
    gradient: "linear-gradient(145deg, #fda4af, #9f1239)",
    bonus: { rangeMul: 1.04 },
    tower: {
      name: "Лунный лук",
      mechanic: "crescent",
      mechanicDesc: "Бонус по замедленным целям",
      cost: 115,
      range: 132,
      damage: 14,
      cooldown: 38,
      color: "#fda4af",
      splash: 0,
      slow: 0,
    },
  },
  {
    id: "nyx",
    name: "Никс",
    role: "Урон +6%",
    rarity: "epic",
    gradient: "linear-gradient(145deg, #a78bfa, #4c1d95)",
    bonus: { damageMul: 1.06 },
    tower: {
      name: "Бездна",
      mechanic: "execute",
      mechanicDesc: "Добивание низких целей",
      cost: 205,
      range: 130,
      damage: 42,
      cooldown: 54,
      color: "#a78bfa",
      splash: 0,
      slow: 0,
    },
  },
  {
    id: "kira",
    name: "Кира",
    role: "Скорострельность +5%",
    rarity: "epic",
    gradient: "linear-gradient(145deg, #fb7185, #9f1239)",
    bonus: { rateMul: 1.05 },
    tower: {
      name: "Шквал",
      mechanic: "volley",
      mechanicDesc: "Залп из трёх снарядов",
      cost: 168,
      range: 112,
      damage: 12,
      cooldown: 22,
      color: "#fb7185",
      splash: 0,
      slow: 0,
    },
  },
  {
    id: "vex",
    name: "Векс",
    role: "Урон +5%",
    rarity: "epic",
    gradient: "linear-gradient(145deg, #2dd4bf, #134e4a)",
    bonus: { damageMul: 1.05 },
    tower: {
      name: "Искажение",
      mechanic: "corrupt_splash",
      mechanicDesc: "Взрыв накладывает порчу (замедление)",
      cost: 188,
      range: 106,
      damage: 22,
      cooldown: 68,
      color: "#2dd4bf",
      splash: 48,
      slow: 0,
    },
  },
  {
    id: "iona",
    name: "Иона",
    role: "Замедление +6%",
    rarity: "epic",
    gradient: "linear-gradient(145deg, #818cf8, #312e81)",
    bonus: { slowMul: 1.06 },
    tower: {
      name: "Громовой шар",
      mechanic: "overload",
      mechanicDesc: "Каждый 3-й выстрел — двойной урон",
      cost: 178,
      range: 118,
      damage: 20,
      cooldown: 58,
      color: "#818cf8",
      splash: 36,
      slow: 0,
    },
  },
  {
    id: "zephyr",
    name: "Зефир",
    role: "Дальность +5%",
    rarity: "epic",
    gradient: "linear-gradient(145deg, #e0e7ff, #4338ca)",
    bonus: { rangeMul: 1.05 },
    tower: {
      name: "Смерч",
      mechanic: "gust_slow",
      mechanicDesc: "Сильный порыв ветра (замедление)",
      cost: 172,
      range: 124,
      damage: 13,
      cooldown: 40,
      color: "#a5b4fc",
      splash: 0,
      slow: 0.28,
    },
  },
  {
    id: "garr",
    name: "Гарр",
    role: "Золото +5%",
    rarity: "epic",
    gradient: "linear-gradient(145deg, #fcd34d, #78350f)",
    bonus: { goldMul: 1.05 },
    tower: {
      name: "Осадный луч",
      mechanic: "siege",
      mechanicDesc: "Широкий радиус взрыва",
      cost: 198,
      range: 108,
      damage: 48,
      cooldown: 102,
      color: "#fcd34d",
      splash: 52,
      slow: 0,
    },
  },
  {
    id: "corin",
    name: "Корин",
    role: "Урон башен +2%",
    rarity: "common",
    gradient: "linear-gradient(145deg, #94a3b8, #334155)",
    bonus: { damageMul: 1.02 },
    tower: {
      name: "Пробойный болт",
      mechanic: "pierce",
      mechanicDesc: "Пробивает до 2 целей подряд",
      cost: 80,
      range: 118,
      damage: 12,
      cooldown: 44,
      color: "#94a3b8",
      splash: 0,
      slow: 0,
    },
  },
  {
    id: "tess",
    name: "Тесс",
    role: "Золото за убийство +4%",
    rarity: "rare",
    gradient: "linear-gradient(145deg, #f97316, #7c2d12)",
    bonus: { goldMul: 1.04 },
    tower: {
      name: "Огненный шар",
      mechanic: "fireball",
      mechanicDesc: "Взрыв по области",
      cost: 118,
      range: 104,
      damage: 20,
      cooldown: 68,
      color: "#fb923c",
      splash: 36,
      slow: 0,
    },
  },
  {
    id: "vorn",
    name: "Ворн",
    role: "Урон +5%",
    rarity: "epic",
    gradient: "linear-gradient(145deg, #38bdf8, #1e3a8a)",
    bonus: { damageMul: 1.05 },
    tower: {
      name: "Цепной разряд",
      mechanic: "chain",
      mechanicDesc: "Цепная молния ко второй цели",
      cost: 192,
      range: 116,
      damage: 19,
      cooldown: 36,
      color: "#38bdf8",
      splash: 0,
      slow: 0,
    },
  },
  {
    id: "brant",
    name: "Брант",
    role: "Дальность +4%, урон +3%",
    rarity: "legendary",
    gradient: "linear-gradient(145deg, #fcd34d, #b45309 60%, #1e293b)",
    bonus: { damageMul: 1.03, rangeMul: 1.04 },
    tower: {
      name: "Луч преломления",
      mechanic: "beam",
      mechanicDesc: "Мгновенный луч без снаряда",
      cost: 228,
      range: 142,
      damage: 38,
      cooldown: 52,
      color: "#fcd34d",
      splash: 0,
      slow: 0,
    },
  },
  {
    id: "sol",
    name: "Соларис",
    role: "Все бонусы +2%",
    rarity: "legendary",
    gradient: "linear-gradient(145deg, #fde047, #b45309)",
    bonus: { damageMul: 1.02, rangeMul: 1.02, slowMul: 1.02, goldMul: 1.02 },
    tower: {
      name: "Солнечный луч",
      mechanic: "beam",
      mechanicDesc: "Мгновенный луч без снаряда",
      cost: 235,
      range: 138,
      damage: 45,
      cooldown: 48,
      color: "#fde047",
      splash: 0,
      slow: 0,
    },
  },
  {
    id: "astra",
    name: "Астра",
    role: "Урон +8%, скорость атаки +3%",
    rarity: "legendary",
    gradient: "linear-gradient(145deg, #f0abfc, #86198f)",
    bonus: { damageMul: 1.08, rateMul: 1.03 },
    tower: {
      name: "Звездопад",
      mechanic: "meteor_pair",
      mechanicDesc: "Второй удар по той же точке",
      cost: 248,
      range: 122,
      damage: 28,
      cooldown: 76,
      color: "#e879f9",
      splash: 58,
      slow: 0,
    },
  },
  {
    id: "nyx",
    name: "Никс",
    role: "Скорострельность +5%",
    rarity: "rare",
    gradient: "linear-gradient(145deg, #a78bfa, #1e1b4b)",
    bonus: { rateMul: 1.05 },
    tower: {
      name: "Теневой разряд",
      mechanic: "chain",
      mechanicDesc: "Цепь: удар по второй цели рядом",
      cost: 148,
      range: 120,
      damage: 18,
      cooldown: 46,
      color: "#a78bfa",
      splash: 0,
      slow: 0,
    },
  },
  {
    id: "gaia",
    name: "Гайя",
    role: "Золото +5%",
    rarity: "rare",
    gradient: "linear-gradient(145deg, #86efac, #064e3b)",
    bonus: { goldMul: 1.05 },
    tower: {
      name: "Алхимический знак",
      mechanic: "midas",
      mechanicDesc: "Мидас: добивание даёт +золото",
      cost: 138,
      range: 112,
      damage: 14,
      cooldown: 34,
      color: "#34d399",
      splash: 0,
      slow: 0,
    },
  },
  {
    id: "orion",
    name: "Орион",
    role: "Урон +6%",
    rarity: "epic",
    gradient: "linear-gradient(145deg, #60a5fa, #0f172a)",
    bonus: { damageMul: 1.06 },
    tower: {
      name: "Осколки небес",
      mechanic: "shrapnel",
      mechanicDesc: "Шрапнель: дополнительный удар по цели рядом",
      cost: 198,
      range: 128,
      damage: 24,
      cooldown: 60,
      color: "#60a5fa",
      splash: 28,
      slow: 0,
    },
  },
  {
    id: "vulcan",
    name: "Вулкан",
    role: "Урон +5%, бронепробитие",
    rarity: "epic",
    gradient: "linear-gradient(145deg, #fb7185, #7f1d1d)",
    bonus: { damageMul: 1.05 },
    tower: {
      name: "Клин расплава",
      mechanic: "armor_pierce",
      mechanicDesc: "Пробивает броню (меньше снижение урона)",
      cost: 210,
      range: 118,
      damage: 30,
      cooldown: 74,
      color: "#fb7185",
      splash: 0,
      slow: 0,
    },
  },
  {
    id: "eidos",
    name: "Эйдос",
    role: "Урон +11%, дальность +5%",
    rarity: "mythical",
    gradient: "linear-gradient(145deg, #22d3ee 0%, #0e7490 45%, #1e1b4b 100%)",
    bonus: { damageMul: 1.11, rangeMul: 1.05 },
    tower: {
      name: "Луч эфира",
      mechanic: "beam",
      mechanicDesc: "Мгновенный луч без снаряда",
      cost: 268,
      range: 152,
      damage: 52,
      cooldown: 46,
      color: "#22d3ee",
      splash: 0,
      slow: 0,
    },
  },
  {
    id: "nebula",
    name: "Небула",
    role: "Все бонусы +4%",
    rarity: "mythical",
    gradient: "linear-gradient(145deg, #e879f9 0%, #7c3aed 50%, #1e1b4b 100%)",
    bonus: { damageMul: 1.04, rangeMul: 1.04, slowMul: 1.04, goldMul: 1.04, rateMul: 1.04 },
    tower: {
      name: "Туманность",
      mechanic: "chain",
      mechanicDesc: "Цепь: удар по второй цели",
      cost: 275,
      range: 132,
      damage: 38,
      cooldown: 42,
      color: "#d946ef",
      splash: 0,
      slow: 0,
    },
  },
  {
    id: "kronos",
    name: "Кронос",
    role: "Урон +10%, скорострельность +6%",
    rarity: "mythical",
    gradient: "linear-gradient(145deg, #fbbf24 0%, #b45309 40%, #0f172a 100%)",
    bonus: { damageMul: 1.1, rateMul: 1.06 },
    tower: {
      name: "Сжатие времени",
      mechanic: "meteor_pair",
      mechanicDesc: "Два удара по одной точке",
      cost: 282,
      range: 128,
      damage: 34,
      cooldown: 68,
      color: "#fcd34d",
      splash: 62,
      slow: 0,
    },
  },
  {
    id: "zenith",
    name: "Зенит",
    role: "Золото +10%, урон +7%",
    rarity: "mythical",
    gradient: "linear-gradient(145deg, #67e8f9 0%, #2dd4bf 35%, #6366f1 100%)",
    bonus: { goldMul: 1.1, damageMul: 1.07 },
    tower: {
      name: "Вершина",
      mechanic: "midas",
      mechanicDesc: "Мидас: доп. золото за убийство",
      cost: 270,
      range: 124,
      damage: 44,
      cooldown: 58,
      color: "#5eead4",
      splash: 36,
      slow: 0,
    },
  },
  {
    id: "silva",
    name: "Сильва",
    role: "Урон +12%, дальность +6%",
    rarity: "verdant",
    gradient: "linear-gradient(145deg, #34d399 0%, #047857 45%, #064e3b 100%)",
    bonus: { damageMul: 1.12, rangeMul: 1.06 },
    tower: {
      name: "Лесной шквал",
      mechanic: "shrapnel",
      mechanicDesc: "Шрапнель: дополнительный удар по цели рядом",
      cost: 288,
      range: 138,
      damage: 46,
      cooldown: 54,
      color: "#10b981",
      splash: 42,
      slow: 0,
    },
  },
  {
    id: "emerin",
    name: "Эмерин",
    role: "Золото +12%, скорострельность +5%",
    rarity: "verdant",
    gradient: "linear-gradient(145deg, #6ee7b7 0%, #059669 40%, #022c22 100%)",
    bonus: { goldMul: 1.12, rateMul: 1.05 },
    tower: {
      name: "Ростки богатства",
      mechanic: "midas",
      mechanicDesc: "Мидас: доп. золото за убийство",
      cost: 292,
      range: 126,
      damage: 42,
      cooldown: 50,
      color: "#2dd4bf",
      splash: 38,
      slow: 0,
    },
  },
  {
    id: "viridian",
    name: "Виридиан",
    role: "Замедление +6%, урон +8%",
    rarity: "verdant",
    gradient: "linear-gradient(145deg, #a7f3d0 0%, #10b981 35%, #14532d 100%)",
    bonus: { slowMul: 1.06, damageMul: 1.08 },
    tower: {
      name: "Лоза холода",
      mechanic: "deep_chill",
      mechanicDesc: "Мороз: сильное замедление",
      cost: 285,
      range: 118,
      damage: 36,
      cooldown: 44,
      color: "#34d399",
      splash: 0,
      slow: 0.4,
    },
  },
];

function getHeroById(id) {
  for (var i = 0; i < HEROES.length; i++) {
    if (HEROES[i].id === id) return HEROES[i];
  }
  return null;
}

function aggregateBonuses(ownedIds) {
  var d = 1,
    r = 1,
    s = 1,
    g = 1,
    rate = 1;
  for (var i = 0; i < ownedIds.length; i++) {
    var h = getHeroById(ownedIds[i]);
    if (!h || !h.bonus) continue;
    var b = h.bonus;
    if (b.damageMul) d *= b.damageMul;
    if (b.rangeMul) r *= b.rangeMul;
    if (b.slowMul) s *= b.slowMul;
    if (b.goldMul) g *= b.goldMul;
    if (b.rateMul) rate *= b.rateMul;
  }
  return { damageMul: d, rangeMul: r, slowMul: s, goldMul: g, rateMul: rate };
}
